### ISSUE TITLE
遊び方書く

### ISSUE THREAD

**Issue by rare0b** [teamdev-c/work-space#41]

**Comment by Seiya-Tagami** [comment]
- テトロミノの挙動は次の通り
右矢印キー = 右方向へ、左矢印キー = 左方向へ、下矢印キー = 下方向へ、上矢印キー = 回転、スペース = 一気に落下
- スコアの加算方式は次の通り
一列消すと10点、二列消すと30点、三列消すと50点、四列消すと70点
